<?php

namespace backend\controllers;

use common\models\adminLoginForm;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends AdminController {

    public function beforeAction ($action) {
        if ($action->id === 'error'){
            $this->layout = 'error';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions () {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex () {
        return $this->render('index');
    }

    public function actionLogin () {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'login';
        $model = new adminLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout () {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}
